shop_pr/cart/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views

router = DefaultRouter()
router.register(r'cart', views.CartViewSet, basename='cart')
router.register(r'admin', views.AdminCartViewSet, basename='admin')

app_name = 'cart'

urlpatterns = [
    path('add_to_cart/<int:product_id>/<int:quantity>', views.add_to_cart, name='add_to_cart'),
    path('delete_cart/', views.delete_cart, name='delete_cart'),
    path('my_cart/', views.CartView.as_view(), name='my_cart'),

    path('api/', include(router.urls)),
]

shop_pr/shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('e_shop.urls')),
    path('user/', include('users.urls')),
    path('cart/', include('cart.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop_pr/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from . import views

router = DefaultRouter()
router.register(r'user', views.UserViewSet, basename='user')
router.register(r'admin', views.AdminUserViewSet, basename='admin')

app_name = 'users'

urlpatterns = [
    path('register/', views.CustomUserCreationView.as_view(), name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('my_profile/', views.profile_view, name='profile'),
    path('edit_profile/', views.ProfileUpdateView.as_view(), name='edit_profile'),

    path('api/', include(router.urls)),

]

shop_pr/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    phone_number = models.CharField(max_length=15, verbose_name='Phone number')

    def __str__(self):
        return self.username

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'


class Address(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE, related_name='addresses')
    street = models.CharField(max_length=100, verbose_name='Street')
    house_number = models.CharField(max_length=10, verbose_name='House number')
    city = models.CharField(max_length=50, verbose_name='City')
    country = models.CharField(max_length=50, verbose_name='Country')
    zip_code = models.CharField(max_length=10, verbose_name='Zip code')

    def __str__(self):
        return f'{self.street}, {self.house_number}, {self.city}, {self.country}'

shop_pr/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser, Address


class CustomUserCreationForm(UserCreationForm):
    street = forms.CharField(max_length=100, required=False, label="Street")
    house_number = forms.CharField(max_length=10, required=False, label="House number")
    city = forms.CharField(max_length=50, required=False, label="City")
    country = forms.CharField(max_length=50, required=False, label="Country")
    zip_code = forms.CharField(max_length=10, required=False, label="Zip code")

    class Meta:
        model = CustomUser
        fields = (
            'username', 'email', 'first_name', 'last_name',
            'phone_number',
        )

    def save(self, commit=True):
        # Сохраняем пользователя
        user = super().save(commit=False)

        if commit:
            user.save()

        address, created = Address.objects.get_or_create(user=user)

        address.street = self.cleaned_data['street']
        address.house_number = self.cleaned_data['house_number']
        address.city = self.cleaned_data['city']
        address.country = self.cleaned_data['country']
        address.zip_code = self.cleaned_data['zip_code']

        if commit:
            address.save()

        return user


class CustomUserChangeForm(forms.ModelForm):
    # Дополнительные поля для редактирования адреса
    street = forms.CharField(max_length=100, required=False)
    house_number = forms.CharField(max_length=10, required=False)
    city = forms.CharField(max_length=50, required=False)
    country = forms.CharField(max_length=50, required=False)
    zip_code = forms.CharField(max_length=10, required=False)

    class Meta:
        model = CustomUser
        fields = ('phone_number',)

    def save(self, commit=True):
        # Сохраняем пользователя
        user = super().save(commit=False)

        address, created = Address.objects.get_or_create(user=user)

        address.street = self.cleaned_data['street']
        address.house_number = self.cleaned_data['house_number']
        address.city = self.cleaned_data['city']
        address.country = self.cleaned_data['country']
        address.zip_code = self.cleaned_data['zip_code']

        # Сохраняем адрес
        if commit:
            address.save()
            user.save()

        return user

shop_pr/users/views.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView
from rest_framework.exceptions import NotFound
from rest_framework.exceptions import PermissionDenied
from rest_framework.permissions import AllowAny
from rest_framework.permissions import IsAdminUser
from rest_framework.viewsets import ModelViewSet

from .forms import CustomUserCreationForm, CustomUserChangeForm
from .models import CustomUser, Address
from .serializers import UserSerializer


class CustomUserCreationView(CreateView):
    form_class = CustomUserCreationForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('e_shop:main_page')


def user_login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            messages.success(request, "You have successfully logged in!")
            return redirect('e_shop:main_page')
        else:
            messages.error(request, "Invalid username or password.")
    else:
        form = AuthenticationForm()

    return render(request, 'users/login.html', {'form': form})


@login_required
def profile_view(request):
    return render(request, 'users/profile.html', {'user': request.user})


class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    model = CustomUser
    form_class = CustomUserChangeForm
    template_name = 'users/profile_edit.html'
    success_url = reverse_lazy('users:profile')

    def get_object(self):
        return self.request.user

    def get_initial(self):
        user = self.request.user
        try:
            address = user.addresses
        except Address.DoesNotExist:
            address = None
        else:

            initial = super().get_initial()

            if address:
                initial['street'] = address.street
                initial['house_number'] = address.house_number
                initial['city'] = address.city
                initial['country'] = address.country
                initial['zip_code'] = address.zip_code

            return initial


class UserViewSet(ModelViewSet):
    """
    Viewset for managing user data.

    This viewset provides endpoints for retrieving and creating user data.
    It is designed to be used for managing the current user's data.
    """

    serializer_class = UserSerializer
    permission_classes = [AllowAny]

    def get_queryset(self):
        """
        Return a queryset of users filtered by the current user's PK if authenticated.

        Raises:
            NotFound: If the user is not authenticated.
        """
        user = self.request.user
        if user.is_authenticated:
            return CustomUser.objects.filter(pk=user.pk)
        raise NotFound('User not found')

    def create(self, request, *args, **kwargs):
        """
        Create a new user.

        This method is only accessible when the user is not authenticated.

        Raises:
            PermissionDenied: If the user is already authenticated.
        """
        if request.user.is_authenticated:
            raise PermissionDenied('Authenticated users cannot create users.')
        return super().create(request, *args, **kwargs)


class AdminUserViewSet(ModelViewSet):
    serializer_class = UserSerializer
    permission_classes = [IsAdminUser]

    def get_queryset(self):
        """
        Return a queryset of all users.

        Returns:
            QuerySet[CustomUser]: A queryset of all users.
        """
        return CustomUser.objects.all()

    def destroy(self, request, *args, **kwargs):
        """
        Delete a user.

        This method is only accessible by admin users.

        Returns:
            Response: A response object with the deleted user's data.

        Raises:
            NotFound: If the user does not exist.
            PermissionDenied: If the user is not an admin.
        """
        return super().destroy(request, *args, **kwargs)

shop_pr/users/templates/users/login.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h1 class="text-center mb-4">Login</h1>

            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {% if messages %}
                            <div class="alert alert-warning">
                                {% for message in messages %}
                                    <p>{{ message }}</p>
                                {% endfor %}
                            </div>
                        {% endif %}

                        <div class="mb-3">
                            <label for="username" class="form-label">Username</label>
                            <input type="text" name="username" id="username" class="form-control" required>
                        </div>

                        <div class="mb-3">
                            <label for="password" class="form-label">Password</label>
                            <input type="password" name="password" id="password" class="form-control" required>
                        </div>

                        <div class="d-grid gap-2">
                            <button type="submit" class="btn btn-primary">Login</button>
                        </div>
                    </form>

                    <div class="mt-3 text-center">
                        <p>Don't have an account? <a href="{% url 'users:register' %}">Register here</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

shop_pr/users/templates/users/profile.html
{% extends 'base.html' %}
{% load card_tag %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h1 class="text-center mb-4">Profile</h1>

            <div class="card">
                <div class="card-body">
                    <h5 class="card-title text-center">Welcome, {{ user.username }}!</h5>

                    <hr>

                    <div class="mb-3">
                        <strong>Email:</strong>
                        <p>{{ user.email }}</p>
                    </div>

                    <div class="mb-3">
                        <strong>First Name:</strong>
                        <p>{{ user.first_name }}</p>
                    </div>

                    <div class="mb-3">
                        <strong>Last Name:</strong>
                        <p>{{ user.last_name }}</p>
                    </div>

                    <div class="mb-3">
                        <strong>Phone Number:</strong>
                        <p>{{ user.phone_number }}</p>
                    </div>

                    <div class="mb-3">
                        <strong>Address:</strong>

                        <p>
                            {{ user.addresses }}
                        </p>
                    </div>

                    <div class="d-grid gap-2">
                        <a href="{% url 'users:edit_profile' %}" class="btn btn-secondary">Edit Profile</a>
                        <a href="{% url 'cart:my_cart' %}" class="btn btn-secondary">View cart</a>
                        <a href="{% url 'users:logout' %}" class="btn btn-danger">Logout</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

shop_pr/users/templates/users/profile_edit.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <h1 class="text-center">Edit Profile</h1>
    <div class="card">
        <div class="card-body">
            <form method="post">
                {% csrf_token %}

                <div class="mb-3">
                    <label for="country" class="form-label">Country</label>
                    <input type="text" name="country" id="country" class="form-control" value="{{ form.country.value }}" required>
                </div>

                <div class="mb-3">
                    <label for="city" class="form-label">City</label>
                    <input type="text" name="city" id="city" class="form-control" value="{{ form.city.value }}" required>
                </div>

                <div class="mb-3">
                    <label for="zip_code" class="form-label">Zip Code</label>
                    <input type="text" name="zip_code" id="zip_code" class="form-control" value="{{ form.zip_code.value }}" required>
                </div>

                <div class="mb-3">
                    <label for="street" class="form-label">Street</label>
                    <input type="text" name="street" id="street" class="form-control" value="{{ form.street.value }}" required>
                </div>

                <div class="mb-3">
                    <label for="house_number" class="form-label">House Number</label>
                    <input type="text" name="house_number" id="house_number" class="form-control" value="{{ form.house_number.value }}" required>
                </div>

                <div class="mb-3">
                    <label for="phone_number" class="form-label">Phone Number</label>
                    <input type="text" name="phone_number" id="phone_number" class="form-control" value="{{ form.phone_number.value }}" required>
                </div>


                <div class="mb-3">
                    <button type="submit" class="btn btn-primary w-100">Save Changes</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

shop_pr/users/templates/users/register.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h1 class="text-center mb-4">Register</h1>
            
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        
                        <div class="mb-3">
                            <label for="username" class="form-label">Username</label>
                            <input type="text" name="username" id="username" class="form-control" value="{{ form.username.value }}">
                        </div>

                        <div class="mb-3">
                            <label for="email" class="form-label">Email address</label>
                            <input type="email" name="email" id="email" class="form-control" value="{{ form.email.value }}">
                        </div>

                        <div class="mb-3">
                            <label for="first_name" class="form-label">First Name</label>
                            <input type="text" name="first_name" id="first_name" class="form-control" value="{{ form.first_name.value }}">
                        </div>

                        <div class="mb-3">
                            <label for="last_name" class="form-label">Last Name</label>
                            <input type="text" name="last_name" id="last_name" class="form-control" value="{{ form.last_name.value }}">
                        </div>

                        <div class="mb-3">
                            <label for="country" class="form-label">Country</label>
                            <input type="text" name="country" id="country" class="form-control" value="{{ form.country.value }}">
                        </div>

                        <div class="mb-3">
                            <label for="city" class="form-label">City</label>
                            <input type="text" name="city" id="city" class="form-control" value="{{ form.city.value }}">
                        </div>

                        <div class="mb-3">
                            <label for="zip_code" class="form-label">Zip Code</label>
                            <input type="text" name="zip_code" id="zip_code" class="form-control" value="{{ form.zip_code.value }}">
                        </div>

                        <div class="mb-3">
                            <label for="street" class="form-label">Street</label>
                            <input type="text" name="street" id="street" class="form-control" value="{{ form.street.value }}">
                        </div>

                        <div class="mb-3">
                            <label for="house_number" class="form-label">House Number</label>
                            <input type="text" name="house_number" id="house_number" class="form-control" value="{{ form.house_number.value }}">
                        </div>

                        <div class="mb-3">
                            <label for="phone_number" class="form-label">Phone Number</label>
                            <input type="text" name="phone_number" id="phone_number" class="form-control" value="{{ form.phone_number.value }}">
                        </div>

                        <div class="mb-3">
                            <label for="password1" class="form-label">Password</label>
                            <input type="password" name="password1" id="password1" class="form-control">
                        </div>

                        <div class="mb-3">
                            <label for="password2" class="form-label">Confirm Password</label>
                            <input type="password" name="password2" id="password2" class="form-control">
                        </div>

                        <div class="d-grid gap-2">
                            <button type="submit" class="btn btn-primary">Register</button>
                        </div>

                    </form>

                    <div class="mt-3 text-center">
                        <p>Already have an account? <a href="{% url 'users:login' %}">Login here</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}