shop_pr/cart/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views

router = DefaultRouter()
router.register(r'cart', views.CartViewSet, basename='cart')
router.register(r'admin', views.AdminCartViewSet, basename='admin')

app_name = 'cart'

urlpatterns = [
    path('add_to_cart/<int:product_id>/<int:quantity>', views.add_to_cart, name='add_to_cart'),
    path('delete_cart/', views.delete_cart, name='delete_cart'),
    path('my_cart/', views.CartView.as_view(), name='my_cart'),

    path('api/', include(router.urls)),
]

shop_pr/e_shop/urls.py
from django.urls import path, include
from . import views
from rest_framework.routers import DefaultRouter

app_name = 'e_shop'

router = DefaultRouter()
router.register(r'products', views.ProductViewSet, basename='product')
router.register(r'categories', views.CategoryViewSet, basename='category')

urlpatterns = [
    path('', views.MainPage.as_view(), name='main_page'),
    path('product/<slug:slug>/', views.DetailProduct.as_view(), name='product'),
    path('<slug:category_slug>/', views.MainPage.as_view(), name='products_by_category'),

    path('api/', include(router.urls)),

]

shop_pr/shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('e_shop.urls')),
    path('user/', include('users.urls')),
    path('cart/', include('cart.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop_pr/e_shop/models.py
from django.db import models
from django.urls import reverse
from django.utils.safestring import mark_safe
from django.utils.text import slugify
from .managers import ProductManager, ProductNotAvailableManager, ProductAllManager


class Category(models.Model):
    """
    Represents a category in the e-shop_pr.

    Attributes:
        name (str): The name of the category.
        parent (Category): The parent category, if any.
        slug (str): The URL-friendly identifier for the category.
        created_at (datetime): The date and time the category was created.
        updated_at (datetime): The date and time the category was last updated.

    Methods:
        __str__(): Returns a string representation of the category.
    """

    name = models.CharField('Category', max_length=255, db_index=True)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')
    slug = models.SlugField('URL', max_length=255, unique=True, null=False, editable=True)
    created_at = models.DateTimeField('Date of create', auto_now_add=True)
    updated_at = models.DateTimeField('Update date', auto_now=True)

    class Meta:
        unique_together = (['parent', 'slug'])
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'
        ordering = ['name']

    def __str__(self):
        """Returns a string representation of the category."""
        category_names = []
        current_category = self
        while current_category is not None:
            category_names.append(current_category.name)
            current_category = current_category.parent
        return ' -> '.join(reversed(category_names))

    def save(self, *args, **kwargs):
        """Save the category, generating a slug if it doesn't exist."""
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        """Returns the URL for the category detail view."""
        return reverse('e_shop:products_by_category', kwargs={'category_slug': self.slug})


class Product(models.Model):
    category = models.ForeignKey('Category', on_delete=models.CASCADE)
    title = models.CharField('Title', max_length=255)
    brand = models.CharField('Brand', max_length=255)
    description = models.TextField('Description')
    slug = models.SlugField('URL', max_length=255, unique=True, null=False, editable=True)
    price = models.DecimalField('Price', max_digits=10, decimal_places=2, default=100.00)
    image = models.ImageField('Image', upload_to='products/%Y/%m/%d', null=True, blank=True)
    available = models.BooleanField('Available', default=True)
    created_at = models.DateTimeField('Date of create', auto_now_add=True)
    updated_at = models.DateTimeField('Update date', auto_now=True)

    objects = ProductManager()
    not_available = ProductNotAvailableManager()
    all_products = ProductAllManager()

    def image_tag(self):
        if self.image:
            return mark_safe(f'<a href="{self.image.url}"><img src="{self.image.url}" width="100" height="100" /></a>')
        return "No Image"

    image_tag.short_description = 'Image'

    class Meta:
        verbose_name = 'Product'
        verbose_name_plural = 'Products'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('e_shop:product', kwargs={'slug': self.slug})

shop_pr/e_shop/views.py
from django.shortcuts import get_object_or_404
from django.views.generic import TemplateView, DetailView
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.filters import OrderingFilter
from rest_framework.permissions import IsAdminUser
from rest_framework.viewsets import ModelViewSet

from .filters import ProductFilter, CategoryFilter
from .models import Category
from .models import Product
from .serializers import CategorySerializer, ProductSerializer


class MainPage(TemplateView):
    template_name = 'e_shop/main_page.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        sort_option = self.request.GET.get('sort')
        cat_slug = kwargs.get('category_slug')

        if cat_slug:
            category = get_object_or_404(Category, slug=cat_slug)
            full_category_name = [category] + list(category.children.all())
            products = Product.objects.filter(category__in=full_category_name)
        else:
            products = Product.objects.all()
            category = None

        if sort_option == 'price_asc':
            products = products.order_by('price')
        elif sort_option == 'price_desc':
            products = products.order_by('-price')
        elif sort_option == 'title_asc':
            products = products.order_by('title')
        elif sort_option == 'title_desc':
            products = products.order_by('-title')
        elif sort_option == 'newest':
            products = products.order_by('-created_at')

        context['products'] = products
        context['category'] = category
        context['categories'] = Category.objects.all()
        return context


class DetailProduct(DetailView):
    model = Product
    template_name = 'e_shop/product.html'
    slug_url_kwarg = 'slug'
    extra_context = {'categories': Category.objects.all()}


class ProductViewSet(ModelViewSet):
    serializer_class = ProductSerializer
    permission_classes = [IsAdminUser]
    queryset = Product.all_products.all()
    filter_backends = [DjangoFilterBackend, OrderingFilter]
    filterset_class = ProductFilter
    ordering_fields = ['price', 'title', 'created_at']


class CategoryViewSet(ModelViewSet):
    serializer_class = CategorySerializer
    permission_classes = [IsAdminUser]
    queryset = Category.objects.all()
    filter_backends = [DjangoFilterBackend, OrderingFilter]
    filterset_class = CategoryFilter
    ordering_fields = ['name', 'created_at']

shop_pr/e_shop/templates/e_shop/main_page.html
{% extends 'base.html' %}

{% block title %}SonwayrShop - Home{% endblock %}

{% block content %}
<!-- Герой-секция -->
<section class="text-center py-5" style="background: linear-gradient(to right, #6a11cb, #2575fc); color: white;">
    <div class="container">
        <h1 class="display-4 fw-bold">SonwayrShop - Fast, Convenient, and Quality</h1>
        <p class="lead">Discover our wide range of products at unbeatable prices!</p>
        <a href="#products" class="btn btn-lg btn-light mt-3">Shop Now</a>
    </div>
</section>

<!-- Альбом продуктов -->
<section id="products" class="py-5">
    <div class="container">
        <h2 class="text-center mb-4">Our Products</h2>
         <!-- Форма сортировки -->
        <form method="GET" class="mb-4">
            <div class="row justify-content-center">
                <div class="col-auto text-center">
                    <label for="sort" class="form-label">Sort by:</label>
                    <select class="form-select" id="sort" name="sort">
                        <option value="">Select...</option>
                        <option value="price_asc" {% if request.GET.sort == "price_asc" %}selected{% endif %}>Price: Low to High</option>
                        <option value="price_desc" {% if request.GET.sort == "price_desc" %}selected{% endif %}>Price: High to Low</option>
                        <option value="title_asc" {% if request.GET.sort == "title_asc" %}selected{% endif %}>Title: A to Z</option>
                        <option value="title_desc" {% if request.GET.sort == "title_desc" %}selected{% endif %}>Title: Z to A</option>
                        <option value="newest" {% if request.GET.sort == "newest" %}selected{% endif %}>Newest</option>
                        <option value="oldest" {% if request.GET.sort == "oldest" %}selected{% endif %}>Oldest</option>
                    </select>
                    <button type="submit" class="btn btn-primary mt-4">Apply</button>
                </div>
            </div>
        </form>
        <div class="row row-cols-1 row-cols-md-2 row-cols-lg-4 g-4">
            {% for product in products %}
            <div class="col">
                <div class="card h-100">
                    {% if product.image %}
                    <div class="card-img-container">
                        <img src="{{ product.image.url }}" style="width: 100%; height: 200px;" alt="{{ product.title }}">
                    </div>
                    {% else %}
                    <div class="card-img-top d-flex align-items-center justify-content-center text-muted"
                         style="height: 200px; background-color: #f8f9fa; border: 1px dashed #ddd;">
                        Photo is not available
                    </div>
                    {% endif %}

                    <div class="card-body d-flex flex-column">
                        <h5 class="card-title">{{ product.title }}</h5>
                        <p class="card-text">Brand: {{ product.brand }}</p>
                        <p class="card-text">Price: ${{ product.price }}</p>
                        <a href="{{ product.get_absolute_url }}" class="btn btn-primary mt-auto">View Details</a>
                    </div>
                </div>
            </div>
            {% empty %}
            <div class="col text-center">
                <p>No products available at the moment.</p>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock %}

<!-- Встроенные стили -->
<style>

section.text-center {
    background: linear-gradient(to right, #6a11cb, #2575fc);
    color: white;
}



.card {
    min-height: 350px;
    display: flex;
    flex-direction: column;
}

.card-body {
    display: flex;
    flex-direction: column;
}

.card-body .btn {
    margin-top: auto; /* Размещение кнопки внизу */
}
</style>

shop_pr/e_shop/templates/e_shop/product.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-6">
            {% if product.image %}
                <img src="{{ product.image.url }}" alt="{{ product.title }}" class="img-fluid rounded">
            {% else %}
                <p>No image available</p>
            {% endif %}
        </div>
        <div class="col-md-6">
            <h1><strong>{{ product.title }}</strong></h1>
            <h1 class="display-6">Category: <a class="btn btn-secondary" href="{{ product.category.get_absolute_url }}" class="display-6">{{product.category }}</a></h1>
            <p class="text-muted">Brand: {{ product.brand }}</p>

            <section class="text-center py-5" style="background: linear-gradient(to right, #6a11cb, #2575fc); color: white;">
                <div class="container">
                    <h1 class="display-6">{{ product.description }}</h1>
                </div>
            </section>

            <h1><strong>Price:</strong> ${{ product.price }}</h1>
            <h1><strong>Availability:</strong>
                {% if product.available %}
                    <span class="badge bg-success">In Stock</span>
                {% else %}
                    <span class="badge bg-danger">Out of Stock</span>
                {% endif %}
            </h1>
            <h1><strong>Listed for sale:</strong> {{ product.created_at|date:"F j, Y, g:i a" }}</h1>
            <a href="{% url 'cart:add_to_cart' product.id 1 %}" class="btn btn-primary mt-4">Add to cart</a>
            <a href="#" class="btn btn-danger mt-4">Buy</a>
            <a href="{% url 'e_shop:main_page' %}" class="btn btn-secondary mt-4">Back to Home</a>

        </div>

    </div>
</div>
{% endblock %}